### ISSUE TITLE
Transactional Services: AccountService listing defines a wrong `get` Account method

### ISSUE THREAD

**Issue by saw303** [grails3book/feedback#1]
Found in Version 0.5, 2017-01-16

This is about the section *Transactional Services*. 

The listing of `AccountController ` and/or `AccountService` is wrong. It seems that the `AccountService#get(Account)` defines a wrong signature.

```groovy
import grails.transaction.Transactional

class AccountController {
  def accountService 
  
  // some code omitted

  def show() { 
    // you read by id
    render accountService.get(params.long('id'))
  }
}
```

but your `AccountService` listing defines the `get` method using an `Account` instance.

```groovy
import grails.transaction.Transactional

@Transactional 
class AccountService {
  // some code omitted

  @Transactional(readOnly = true)
  // This method is never called in AccountController
  def get(Account account) {
    return account
  }
}
```

Change the signature to 

```groovy
import grails.transaction.Transactional

@Transactional 
class AccountService {
  // some code omitted

  @Transactional(readOnly = true)
  def get(Long accountId) {
    return Account.get(accountId)
  }
}
```

**Comment by erichelgeson** [comment]
Thanks! This is actually one section I haven't moved over to including straight from the source files (which would have caught this error!) Next version will have this in the intro-examples app with tests.
