### ISSUE TITLE
depencencies misspelled

### ISSUE THREAD

**Issue by rlovtangen** [grails3book/feedback#11]
## What release of the book did you find the issue in?
0.5, 2017-01-16
## Describe the issue or feedback. 

In the chapter "Configuring spring-security-rest", "dependencies" is misspelled:

```
dependancies {
    compile "org.grails.plugins:spring-security-rest:2.0.0.M2"
}
```
should be:

```
dependencies {
    compile "org.grails.plugins:spring-security-rest:2.0.0.M2"
}
```

Also a few other places where "dependencies" is misspelled. Easily fixed by a search and replace.

**Comment by erichelgeson** [comment]
Thanks.. slightly annoying that atom will suggest the miss-spelled word if it comes first! May have to switch editors to something with a better spell check.
