### ISSUE TITLE
(small) typo - Transactional Services section

### ISSUE THREAD

**Issue by catharpin** [grails3book/feedback#12]
## What release of the book did you find the issue in?
version 0.5, 2017-01-16, Grails 3.2.4

## Describe the issue or feedback. 
Transactional Services
----

Controllers and views for __convince__ - unintended data access

likely should be "for convenience"

**Comment by erichelgeson** [comment]
Thanks - need a better spell checker then what Atom provides! :)

**Comment by catharpin** [comment]
NP.  Spellcheck wouldn't have caught that anyway.  Overall I want to say the tone and approach of the book is really solid and explains topics clearly and succinctly - topics where much of what's out there either skips entirely or gets reference-manual-itis; looking forward to the rest.
