### ISSUE TITLE
biography Property missing from Author

### ISSUE THREAD

**Issue by mdenieffe** [grails3book/feedback#13]
Version 0.5, 2017-01-16, Grails 3.2.4

Section 2: Example Application > Building our Domain

Minor issue, but when creating an **Author** and a **Book** in the **Bootstrap.groovy** you reference a **biography** property that doesn't exist on the **Author** class. 

`def eric = new Author(name: "Eric", biography: "Grails Developer & Writer").save()`

**Comment by erichelgeson** [comment]
Fixed
