### ISSUE TITLE
Adding Properties -> Grails vs Groovy, odd sentence.

### ISSUE THREAD

**Issue by supsup** [grails3book/feedback#15]
## What release of the book did you find the issue in?
.5

## Describe the issue or feedback. 

> Grails is adding a lot behind the scenes here to make our life easier. You can see we did not define any getters, setters, and finders on this class, though as you’ll see in the next section we can use them. Groovy allows you to skip much of the "boilerplate" code making your app more expressive.

You mention Grails doing things that Groovy does, then switch to Groovy in the second sentence, a little confusing.

Suggested: (something like)

Grails by leveraging Groovy, reduces "boilerplate" code in your app, making your app more expressive. We did not define any getters, setters, and finders on this class, though as you’ll see in the next section we can use them.  

--or maybe not, just a new person to Grails might think it's Grails giving you those properties instead of Groovy.  Grails does make your life easier, but none of the examples you gave are because of Grails directly.

**Comment by erichelgeson** [comment]
Fixed in next release, thanks!
