### ISSUE TITLE
Nit picky pronoun destroyer, being exact regardless of step context

### ISSUE THREAD

**Issue by supsup** [grails3book/feedback#16]
## What release of the book did you find the issue in?
0.5

## Describe the issue or feedback. 
In the Data Binding section

> We tell this endpoint to expect a Person object.
> Calling save() will return false if there are validation errors.

I think the following would would be easier to follow:

We tell the ExampleController's save endpoint to expect a Person object.
Calling person.save() will return false if there are validation errors.

--argument can be made the numbers give enough context, and this suggestion is too verbose.

**Comment by erichelgeson** [comment]
Fixed in the next version, thanks!
