### ISSUE TITLE
Text switches from talking about a Person to a Book.

### ISSUE THREAD

**Issue by supsup** [grails3book/feedback#17]
## What release of the book did you find the issue in?
0.5

## Describe the issue or feedback. 
In the Data Binding section the text switches from talking about a Person to a Book.

> We tell this endpoint to expect a **Person object**. Grails will look at the incoming request and see if there is a params.id, if so grab that **book** from the database. If not create a new **book object** and bind any properties that match the properties on the **Book domain class**.

**Comment by supsup** [comment]
Also step #5 has book ref:

> 	If the **book** was saved to the database we can respond back with that object.

**Comment by erichelgeson** [comment]
Fixed in next version, thanks for the report!
