### ISSUE TITLE
Consider adding example for Spring Security Authentication and Authorization Integration

### ISSUE THREAD

**Issue by edwardotis** [grails3book/feedback#19]
## Describe the issue or feedback. 
Authentication and Authorization is a fundamental concern for almost every real world app. However, the top Spring Security and Spring Security UI plugins do not work out of the box with hibernate backed web app.

The only way to get it working is track down the github issues, and keep trying suggestions to fix it.
For example, this github issue has the key hack to get it spring-security, hibernate4 and grails3.x working:
https://github.com/grails-plugins/grails-cache-ehcache/issues/26

Adding in a functional example project to the book would be immensely useful for people who desire to build database backed apps that require authentication and authorization. 

Thank you for your consideration.

**Comment by edwardotis** [comment]
Now I see that beckwith has created an example that uses the hack. It's not listed in the spring-security documentation as far as I can tell.
https://github.com/grails-plugins/grails-spring-security-core/tree/master/secured

And the ehcache hack is listed as a footnote in Chapter 12.3.1 of the official instructions, but I only found that because I now know to search for the ehcache exclude.
https://grails-plugins.github.io/grails-spring-security-core/v3/index.html#locking

So, not a good experience for new grails users.

**Comment by erichelgeson** [comment]
Hi @edwardotis - 

Your assertion that Spring-Security does not work out of the box with a hibernate backed grails app is incorrect - You've added a dependency to the ehcache plugin which is not included in an "out of the box" grails app.

There are many times when a plugin or transitive dependency will cause issues between spring/grails/plugins/etc. I will call those out if needed for the examples in the book - but none of my example would hit this issue. I would not consider a transitive dependency exclude a "hack".

I see you've replied to multiple repos with this same concern - I will let the plugin maintainers address your concerns and be sure to call out any additional configuration needed in examples in the book.

Lastly - SpringSecurity UI will not be included in the book. From my experience it is quicker (and you learn a lot more) by implementing the features it provides.

Thanks,
