### ISSUE TITLE
Callout misses description

### ISSUE THREAD

**Issue by sbglasius** [grails3book/feedback#2]
## What release of the book did you find the issue in?
Version 0.5, 2017-01-16
## Describe the issue or feedback. 
In describing `BootStrap.groovy` for the first time you have 5 bullets in the code, but only four of them is described.

![image](https://cloud.githubusercontent.com/assets/625868/22012317/aa76aa7c-dc93-11e6-844e-51a2aa0f7153.png)

**Comment by erichelgeson** [comment]
Thanks! Also odd, asiidoctor usually warns me about such things. Will be addressed in the next version.
