### ISSUE TITLE
Transactional Services - 'convince' instead of 'convenience'?

### ISSUE THREAD

**Issue by brownidj** [grails3book/feedback#20]
Version 0.5, 2017-01-16, Grails 3.2.4

First sentence in this section. I'm not sure how you'd like to be notified of minor spelling/spell-checking issues. Doing them one by one seems laborious. OTH, a list virtually ensures a lot of duplication. Perhaps some guidance from your end would be best - after all you're the guy who as to deal with them!

Thanks - and I'm looking forward to new sections

David

**Comment by erichelgeson** [comment]
Hi, Thanks for the report.

Minor typos are appreciated - email works too if you just want to enumerate them. Though closer to final release the book will go through an editor to catch these as well.
