### ISSUE TITLE
Working with the Request -> Incoming JSON example don't work

### ISSUE THREAD

**Issue by pablolucero** [grails3book/feedback#21]
## What release of the book did you find the issue in?
0.5
## Describe the issue or feedback. 
the curl example lacks the argument `-H "Accept: application/json"`

also I think its a good idea add the example that will work after the changes:

`curl -i -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d "{'name':'Jason'}" http://localhost:8080/example/hello`

**Comment by erichelgeson** [comment]
Thanks, already fixed, should be a new copy out in a week or so! Moving these CLI examples to includes so they can be tested automatically before each release too :)
