### ISSUE TITLE
SpringSecurity Config: Use Application.yml instead Application.groovy

### ISSUE THREAD

**Issue by acrive82** [grails3book/feedback#22]
Application.groovy is an old style practice. Please provide a configuration for Spring Security in YAML.

**Comment by erichelgeson** [comment]
`grails-app/conf/application.groovy` is new in Grails 3 (not to be confused with `Config.groovy` in previous versions. Grails will also pick up config from an `grails-app/conf/application.yml` (or many other locations/properties)[1] - but in my recommendation is to use the groovy version as it allows a lot of flexibility. The great thing is you can chose how to inject config and properties in a way that fits your deployment needs. 

In fact spring-security-core plugin you mention generates the application.groovy file for you[2]

Providing a yml copy of the same key/values does not provide much value.

[1] https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html
[2] https://github.com/grails-plugins/grails-spring-security-core/blob/7f09c528bedcf53ff9d109dad725d68a54d36a2e/src/docs/introduction/configGroovy.adoc
